### ISSUE TITLE
Solver has problems with levels with two beam samplers but only two targets

### ISSUE THREAD

**Issue by XenoBene** [tom-kaufman/laser-mazer#4]
When you try to solve a level where two beam sampler are used but only two targets need to be hit (for example Bonus Challenge 2), the solution that will be found is actually wrong. One beam leaves the field.

This happens with all of these kind of 2 beam sampler/ 2 target levels.

**Comment by tom-kaufman** [comment]
Thanks for reporting this issue I'll take a look! Just wondering, how did you find this project?

**Comment by XenoBene** [comment]
I am a phd student (laser physics) from Germany, and our group stumbled upon LaserMaze by chance. We are doing a daily challenge with a highscore board, so one level per day and the fastest one gets the point ;) We are currently at bonus challenge 55.

We were thinking about how to solve these levels with the help of code, when we found your project by googling „Laser Maze Solver“. Very nice work by the way!

We are also designing our own levels just for fun (without the help of code); so if you want some more challenges just let me know ;)

**Comment by tom-kaufman** [comment]
Hey @XenoBene, I've just sat down to look at this bug, but I'm seeing that ThinkFun may have taken down the bonus challenges from their website. The pdf for the game rules linked in this project's readme is also now a dead link!

Do you happen to have a copy of the bonus challenges..?

**Comment by tom-kaufman** [comment]
Luckily I have Bonus Challenge 2 saved into this project for debugging this issue :) Does this match your solution for the puzzle? It's a bit weird that the puzzle can have 2 splitters and only 2 target mirrors. But I guess the yellow checkpoint token functions as a 3rd target?

![image](https://github.com/user-attachments/assets/dbd9dd53-2201-4f0d-ad67-f763feeb46f6)

**Comment by XenoBene** [comment]
Oh, that is unfortunate! Yeah, luckily I have downloaded all bonus levels beforehand because we printed them all out.
Attached is the first half of the bonus levels.
[LaserMaze_Part1.pdf](https://github.com/user-attachments/files/17265435/LaserMaze_Part1.pdf)

**Comment by XenoBene** [comment]
As for bonus level 2:
The levels with two beam splitters but only two targets follow a different kind of logic. You have to merge the two beams from the first beam splitter with the second splitter.

I am currently away from my PC, but attached is my self drawn solution. I can send you more information on these kind of levels tomorrow!
![Solution2](https://github.com/user-attachments/assets/36b49dde-9d4d-46aa-82ea-a5bec31f8d5d)

**Comment by tom-kaufman** [comment]
Fixed in #5 and new binaries will be on the releases page shortly. Thanks again @XenoBene for the bug report, please let me know if you find other issues and good luck with your research!

**Comment by tom-kaufman** [comment]
By the way @XenoBene could you provide the other bonus challenges? I want to include them in this project at some point

**Comment by XenoBene** [comment]
[LaserMaze_Part1.pdf](https://github.com/user-attachments/files/17530329/LaserMaze_Part1.pdf)
[LaserMaze_Part2.pdf](https://github.com/user-attachments/files/17530331/LaserMaze_Part2.pdf)
[LaserMaze_Part3.pdf](https://github.com/user-attachments/files/17530332/LaserMaze_Part3.pdf)
[LaserMaze_BonusChallenges_Solutions.txt](https://github.com/user-attachments/files/17530347/LaserMaze_BonusChallenges_Solutions.txt)

Nice work! I tested it with a few bonus challenges and it works fine.
Attached are all the bonus challenges, I had them ready because we had them printed out physically. Also attached are the solutions to every bonus challenge, I got them from a request to ThinkFun a few months ago. 

That being said, some of the bonus challenges are actually unsolvable because they made a mistake while putting them together. It only affects 2-3 challenges, but I unfortunately don't remember which ones… The solutions in text form show the correct placement, so if your solver says that one level is unsolvable, you have to look at the solutions. BUT the solutions are actually not numbered in the right order… So you have to search a bit unfortunately. That's on ThinkFun, not me ;)
